name: tiktaktoe
description: A two-player animated Tic-Tac-Toe match game
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/winner.json
